node {
    git branch: 'master',
    url: 'https://github.com/difki/azure-voting-app-redis.git'
    
  stage('Change versions') {
    withKubeConfig([credentialsId: 'forcli',
                    ]) {
      sh 'pwd;ls;kube/config.sh'
    }
  }
  stage('kubectl apply') {
    withKubeConfig([credentialsId: 'forcli',
                    ]) {
      sh 'kubectl apply -f kube/'
      sh 'kubectl rollout status deployment.apps/nginx-deployment'
      sh 'kubectl get pods'
    }
  }
  stage('List pods ') {
    withKubeConfig([credentialsId: 'forcli',
                    ]) {
      sh 'kubectl rollout status deployment.apps/nginx-deployment'
      sh 'kubectl get pods'
    }
  }
}
